### PR TITLE
fix(ses): missing native function markings

### LINKED ISSUE #1228: Function.toString is not marked as native code
image

### PR DESCRIPTION
**Pull request by erights**
Fixes #1228 
Fixes https://github.com/endojs/endo/issues/835

The replacement `Function.prototype.toString`, which uses the synthetic native function marking, should itself have been marked as a native function, so that it would recognize itself as such. First, I saw I needed to install it early. But it still wasn't being marked, which was quite puzzling. Turns out there was a bug in the marking logic in the whitelist-intrinsics code, where functions could both skip being marked, or could be pointlessly marked redundantly.

@Jack-Works , please consider yourself a reviewer of this PR. I look forward to your comments. And thanks for the original report! If I hadn't investigated I would not have found this deeper bug.

Turns out that this deeper bug was already reported by @kriskowal at #835

### CODE REVIEW

**Review by Jack-Works — APPROVED** [review]

File: packages/ses/src/whitelist-intrinsics.js [hunk 1]
```diff
@@ -261,6 +260,10 @@ export default function whitelistIntrinsics(
     const protoName = permit['[[Proto]]'];
     visitPrototype(path, obj, protoName);
 
+    if (typeof obj === 'function') {
+      markVirtualizedNativeFunction(obj);
+    }
```
Comment (kriskowal) [inline packages/ses/src/whitelist-intrinsics.js:265]: Yes!

**Comment by erights** [comment]
@kriskowal FYI I still need your approval

**Review by kriskowal — APPROVED** [review]
