### PR TITLE
test(ses-types-test): Adds basic external types validation for SES

### LINKED ISSUE #777: SES fails to export type for harden
SES is exporting harden with the type `any`. At the least, we need an external type test package within SES to verify that the types are exported properly, usably. It might be necessary to write the `harden` definition in TS within `index.d.ts` instead of relying on a type signature imported from JS.

cc @dckc

### PR DESCRIPTION
**Pull request by kriskowal**
Fixes #777

### CODE REVIEW

File: packages/ses-types-test/test/test-ses.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+/// <reference types="ses"/>
+
+import test from 'ava';
+
+lockdown();
+
+test('harden', t => {
+  const { x, y } = harden({ x: 4, y: 3 });
```
Comment (dckc) [inline packages/ses-types-test/test/test-ses.js:8]: I don't see how this would fail if `harden` got a type of `any`. Help?

Comment (kriskowal) [reply packages/ses-types-test/test/test-ses.js:8]: Huh, good point. It doesn’t fail if I remove the reference. Will have to phone a friend.

Comment (mhofman) [reply packages/ses-types-test/test/test-ses.js:8]: You could probably negate the test.
```suggestion
  // @ts-expect-error
  const { z } = harden({ x: 4, y: 3 });
```

**Comment by mhofman** [comment]
Is there a reason these type tests need to actually execute instead of just going through the type checker?

Also while it's probably good to check compatibility with jsdoc typing usage, it's likely easier to just write pure TypeScript for type tests.

**Comment by kriskowal** [comment]
> Is there a reason these type tests need to actually execute instead of just going through the type checker?
> 
> Also while it's probably good to check compatibility with jsdoc typing usage, it's likely easier to just write pure TypeScript for type tests.

I would like to pair with you. I’ll pilot. You navigate.

File: packages/ses/NEWS.md [hunk 2]
```diff
@@ -2,6 +2,9 @@ User-visible changes in SES:
 
 # Next version
 
+- Adds more TypeScript definitions, importable with `/// <reference
+  types="ses"/>`, covering `harden`, `lockdown`, `assert`, and `Constructor`,
```
Comment (mhofman) [inline packages/ses/NEWS.md:6]:
```suggestion
  types="ses"/>`, covering `harden`, `lockdown`, `assert`, and `Compartment`,
```

File: packages/ses/src/lockdown-shim.js [hunk 3]
```diff
@@ -324,6 +311,7 @@ export const repairIntrinsics = (
  * @param {CompartmentConstructorMaker} makeCompartmentConstructor
  * @param {Object} compartmentPrototype
  * @param {() => Object} getAnonymousIntrinsics
+ * @returns {import('../index').Lockdown}
```
Comment (mhofman) [inline packages/ses/src/lockdown-shim.js:314]:
```suggestion
 * @returns {import('../index.js').Lockdown}
```

File: packages/ses-types-test/test/test-ses.js (hunk 1 above)
Comment (mhofman) [reply packages/ses-types-test/test/test-ses.js:8]: Do we still need this file?

**Review by mhofman — CHANGES_REQUESTED** [review]
Thanks so much for doing this!

File: packages/ses-types-test/validation.ts [hunk 4]
```diff
@@ -0,0 +1,148 @@
+/* eslint-disable no-unused-vars, no-underscore-dangle */
+/// <reference types="ses"/>
+
+// eslint-disable-next-line prettier/prettier
```
[the remark this answers is not in the document]
Comment (kriskowal) [reply packages/ses-types-test/validation.ts:4]: Prettier is confused for the next line. It thinks there should be an `=` in there.

File: packages/ses/index.d.ts [hunk 5]
```diff
@@ -1,52 +1,133 @@
...
-// For scripts.
-declare var harden: Hardener;
-declare var lockdown: Lockdown;
-declare var Compartment : ReturnType<CompartmentConstructor>;
-declare var StaticModuleRecord : StaticModuleRecord;
-
-declare type StaticModuleType = RedirectStaticModuleInterface | FinalStaticModuleType;
-declare interface RedirectStaticModuleInterface {
+
+export type Harden = <T>(value: T) => T;
```
[the remark this answers is not in the document]
Comment (kriskowal) [reply packages/ses/index.d.ts:2]: I’m going to run with `Harden` because it wasn’t exported previously, I’d rather not `Lockdowner` for consistency, and there won’t be a follow-up just for that change.

File: packages/ses-types-test/validation.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (mhofman) [reply packages/ses-types-test/validation.ts:4]: So I looked into this and it seems that the parser used by the prettier eslint plugin somehow isn't up to date. I have no idea why because the eslint parser itself is fine (`"@typescript-eslint/parser": "^4.25.0"`). In general I'm not a big fan of prettier integrated inside of eslint, and this might be another reason we want to kill it, but that's a battle for another day.

**Review by mhofman — APPROVED** [review]

**Comment by kriskowal** [comment]
I’ve added two commits necessary to complete type verification internally, and to belatedly address @mhofman’s feedback from https://github.com/endojs/endo/pull/784 These changes thread the types from SES through StaticModuleRecord and Compartment Mapper, removing type ambience in these cases.

File: packages/compartment-mapper/src/bundle.js [hunk 6]
```diff
@@ -56,7 +67,10 @@ const sortedModules = (
     if (source) {
       const { record, parser } = source;
       if (record) {
-        const { imports = [], reexports = [] } = record;
+        const {
+          imports = [],
+          reexports = [],
+        } = /** @type {PrecompiledStaticModuleInterface} */ (record);
```
Comment (mhofman) [inline packages/compartment-mapper/src/bundle.js:73]: Probably dumb question, but there's no way the `record` is a `ThirdPartyStaticModuleInterface` here?
I wasn't sure originally why the casting was necessary.

File: packages/compartment-mapper/src/import-hook.js [hunk 7]
```diff
@@ -1,11 +1,27 @@
...
 
 // q, as in quote, for quoting strings in error messages.
 const q = JSON.stringify;
 
 const { apply } = Reflect;
-const { freeze } = Object;
+
+/**
+ * TypeScript cannot be relied upon to deal with the nuances of Readonly, so we
+ * borrow the pass-through type definition of harden here.
```
Comment (mhofman) [inline packages/compartment-mapper/src/import-hook.js:19]: Isn't it dangerous if we ever update the definition of `Harden` to be more correct? I might be of the opinion to just be explicit here by copying the current passthrough definition of `Harden`

File: packages/compartment-mapper/src/parse-archive-cjs.js [hunk 8]
```diff
@@ -39,6 +43,11 @@ export const parseArchiveCjs = async (
   return {
     parser: 'pre-cjs-json',
     bytes: pre,
-    record: freeze({ imports, exports, reexports }),
+    record: /** @type {ThirdPartyStaticModuleInterface} */ (freeze({
+      imports,
+      exports,
+      reexports,
+      execute: noopExecute,
```
Comment (mhofman) [inline packages/compartment-mapper/src/parse-archive-cjs.js:50]: Since I'm not qualified yet to review any runtime changes, I assume `execute` was never used before but required in types?

File: packages/compartment-mapper/src/parse-json.js [hunk 9]
```diff
@@ -2,19 +2,24 @@
 
 import { parseLocatedJson } from './json.js';
 
-const { freeze } = Object;
+/**
+ * TypeScript cannot be relied upon to deal with the nuances of Readonly, so we
+ * borrow the pass-through type definition of harden here.
+ *
+ * @type {import('ses').Harden}
```
Comment (mhofman) [inline packages/compartment-mapper/src/parse-json.js:9]: Same comment here (maybe we need a `LaxFreeze` in `types.js`)

File: packages/compartment-mapper/src/parse-archive-cjs.js [hunk 10]
```diff
@@ -1,13 +1,17 @@
...
+
 import { analyzeCommonJS } from '@endo/cjs-module-analyzer';
 
 const textEncoder = new TextEncoder();
 const textDecoder = new TextDecoder();
 
 const { freeze } = Object;
 
-/** @type {ParseFn} */
+const noopExecute = () => {};
```
Comment (mhofman) [inline packages/compartment-mapper/src/parse-archive-cjs.js:12]: Should `noopExecute` be frozen?

**Review by mhofman — APPROVED** [review]
LGTM, just a couple nits

File: packages/compartment-mapper/src/bundle.js (hunk 6 above)
Comment (kriskowal) [reply packages/compartment-mapper/src/bundle.js:73]: Yeah, the necessity of casting perplexed me too, since `record` in this position can be either a `PrecompiledStaticModuleInterface` or `ThirdPartyStaticModuleInterface`, but only the former has a `reexports`, and the default `[]` is sufficient in all cases when `record` is 3rd party. This is trickery, but it works for both cases because of the default.

File: packages/compartment-mapper/src/import-hook.js (hunk 7 above)
Comment (kriskowal) [reply packages/compartment-mapper/src/import-hook.js:19]: I figured out that it will be a devastating breaking change to make the `Harden` type definition correct regardless. It’s the kind of breaking change that would require TypeScript to grow a new head before we could even contemplate it. I don’t think this digs our heels in too badly. If we do introduce a `ProperHarden` type, it’ll need a different name and a long migration period to propagate outward.

File: packages/compartment-mapper/src/parse-archive-cjs.js (hunk 8 above)
Comment (kriskowal) [reply packages/compartment-mapper/src/parse-archive-cjs.js:50]: Correct. We don’t execute a module when it’s on its way into a Zip file.

File: packages/compartment-mapper/src/parse-json.js (hunk 9 above)
Comment (kriskowal) [reply packages/compartment-mapper/src/parse-json.js:9]: Antifreeze?

File: packages/compartment-mapper/src/parse-archive-cjs.js (hunk 10 above)
Comment (kriskowal) [reply packages/compartment-mapper/src/parse-archive-cjs.js:12]: Good idea. I’ll do this.

File: packages/compartment-mapper/src/bundle.js (hunk 6 above)
Comment (mhofman) [reply packages/compartment-mapper/src/bundle.js:73]: Yeah the problem is you cannot access a property that doesn't exist in one of the types in a union. An alternative trick might be to specify the `ThirdPartyStaticModuleInterface` differently: 

```
export interface ThirdPartyStaticModuleInterface {
  imports: Array<string>;
  exports: Array<string>;
  reexports?: void;
  execute(proxiedExports: Object, compartment: Compartment, resolvedImports: Record<string, string>): void;
}
```
