### PR TITLE
fix(ses): Fix {} error reports

### LINKED ISSUE #769: Fix error recovery for Node.js and web
In the attached gist, the `hazard.js` module trips the property override hazard that results from SES lockdown. The `mitigation.js` demonstrates that using the Node.js `uncaughtException` handler (and by extension, the web’s `window.addEventListener("error", handler)`), we can restore a meaningful error message by trapping the tamed error and passing it to the tamed console. Allowing the error to fall through without a handler fails through to the platform, which does not delegate to the tamed console and so writes `{}` instead of a meaningful error.

https://gist.github.com/kriskowal/96fc21ada2e280821b405e12cdadd00a

It might also be nice if the tamed error had an appropriate stringifier so at least the message gets revealed if SES cannot sniff a platform error hook.

### PR DESCRIPTION
**Pull request by kriskowal**
Errors are reported as `{}` when they are caught by Node.js or the web runtime because their stacks are censored. They must be caught with a platform hook and passed to the tamed console to reveal their stack. 

- test(ses): Test error output on Node.js (a failing test)
- fix(ses): Trap and report errors (fixes failing test)

Must be merged to keep the left traversal on git bisectable with passing tests.

Fixes #769

### CODE REVIEW

**Comment by erights** [comment]
Congrats on the following CI failure. Seriously. It is great that this is now a fail-stop failure with a reasonable diagnostic. It will be interesting to find out how sloppy mode crept back in.

```
Error: Unexpected exception Error: Error: SES failed to initialize, sloppy mode (SES_NO_SLOPPY)
```

**Comment by kriskowal** [comment]
> Congrats on the following CI failure. Seriously. It is great that this is now a fail-stop failure with a reasonable diagnostic. It will be interesting to find out how sloppy mode crept back in.
> 
> ```
> Error: Unexpected exception Error: Error: SES failed to initialize, sloppy mode (SES_NO_SLOPPY)
> ```

Indeed. My next great mystery, considering nothing related has changed!

File: packages/ses/src/error/tame-console.js [hunk 1]
```diff
@@ -37,5 +38,34 @@ export const tameConsole = (
     };
   }
   const causalConsole = makeCausalConsole(originalConsole, loggedErrorHandler);
+
+  // Attach platform-specific error traps such that any error that bottoms out
+  // an event will get unwrapped by the causal console, revealing the error
+  // stack to the console for debugging.
```
Comment (erights) [inline packages/ses/src/error/tame-console.js:44]: By "event" do you mean "turn"? I haven't been using the term "unwrapped", though I don't have an alternative on top of my head. The console reveals not just the stack but the full unredacted detailed error message, and attached notes, including their errors, etc...


```suggestion
  // Attach platform-specific error traps such that any error that gets thrown at top-of-turn (i.e., bottom of stack) will 
  // get logged by our causal console, revealing the diagnostic information associated with the error, including the
  // stack from when the error was created.
```

File: packages/ses/src/error/tame-console.js [hunk 2]
```diff
@@ -37,5 +38,34 @@ export const tameConsole = (
...
+  // Node.js
+  if (
+    typeof process === 'object' &&
+    process !== null &&
+    typeof process.on === 'function' &&
+    typeof process.exit === 'function'
+  ) {
+    process.on('uncaughtException', error => {
+      causalConsole.error(error);
+      process.exit(process.exitCode || -1);
```
Comment (erights) [inline packages/ses/src/error/tame-console.js:55]: We cannot do that in general. That would enable confined code to cause the node process running it to exit. Causing the node process to exit *must* require some privilege.

File: packages/ses/test/test-console-error-trap.js [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+  exec('node index.js', { cwd }, (err, stdout, stderr) => {
+    t.assert(err, 'exit code should be non-zero');
+    t.assert(
+      stderr.includes('(Error#1)'),
+      'stderr should have an error marker',
+    );
+    t.assert(
+      stdout.includes('Error#1: Shibboleth'),
+      'stdout should contain error message',
+    );
```
Comment (erights) [inline packages/ses/test/test-console-error-trap.js:21]: Why is some console output going to stdout and some going to stderr? Did I screw something up in the console implementation?

File: packages/ses/test/test-console-error-trap.js [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+
+const cwd = join(
+  dirname(new URL(import.meta.url).pathname),
+  'console-error-trap',
+);
+
+test.cb('errors reveal their stacks', t => {
+  t.plan(3);
+  exec('node index.js', { cwd }, (err, stdout, stderr) => {
+    t.assert(err, 'exit code should be non-zero');
```
Comment (erights) [inline packages/ses/test/test-console-error-trap.js:13]:
```suggestion
    t.assert(err !== 0, 'exit code should be non-zero');
```
I do sometimes wonder how much we should rely on the reader's knowledge of JS's rules of truthiness and falsiness. I don't have a strong opinion on this one.

File: packages/ses/test/test-console-error-trap.js [hunk 5]
```diff
@@ -0,0 +1,24 @@
+import test from 'ava';
+import { exec } from 'child_process';
+import { dirname, join } from 'path';
+
+const cwd = join(
+  dirname(new URL(import.meta.url).pathname),
+  'console-error-trap',
+);
+
+test.cb('errors reveal their stacks', t => {
```
Comment (erights) [inline packages/ses/test/test-console-error-trap.js:10]: What is `test.cb`? I don't remember.

**Review by erights — CHANGES_REQUESTED** [review]
Can't allow unprivileged code to cause the enclosing Node process to exit.

The sniffing here is necessarily host specific, so we can incrementally add hosts over time. What are your thoughts on what we should do on xsnap, where the entire console is our own creation anyway? Is it even possible on current xsnap to catch these errors?

File: packages/ses/test/test-console-error-trap.js (hunk 4 above)
Comment (dckc) [reply packages/ses/test/test-console-error-trap.js:13]: I like to use the typescript checker as a very careful but not very knowledgeable reader. `tsc` should be told (by the callee) what type is expected. Then it can carefully check that expectations are met. For example:

```js
/** @param {unknown} x */
function truthy(x) { return !!x; }

truthy('abc'); // OK

/** @param {boolean} condition */
function isTrue(condition) { return condition === true; }

isTrue('abc'); // Argument of type 'string' is not assignable to parameter of type 'boolean'.ts(2345)
```

Downsides:
  1. Until we get to a pretty strict "no any" policy (#600), nothing ensures that the callee provided such a declaration and the default is `any`... so callers trained as above might infer from lack of a red squiggle that they're doing it right when in fact lack of a red squiggle just means tsc didn't check it.
  2. Conversely, callees have to keep in mind that type declarations are static advisory checks, not runtime defensive correctness guarantees.

File: packages/ses/test/test-console-error-trap.js (hunk 3 above)
Comment (kriskowal) [reply packages/ses/test/test-console-error-trap.js:21]: Aye, we should make sure to use `console.log` only for `stdout`. We currently use a mix.

File: packages/ses/test/test-console-error-trap.js (hunk 4 above)
Comment (kriskowal) [reply packages/ses/test/test-console-error-trap.js:13]: I’ll check on the type. I think it’s an `Error` that may have a `code` number property, not a number itself.

File: packages/ses/test/test-console-error-trap.js (hunk 5 above)
Comment (kriskowal) [reply packages/ses/test/test-console-error-trap.js:10]: I don’t either, but it was used in the packaging test after it got ported to Ava so I’ll look it up to learn why. Probably ensures that the test ends at `t.end()` instead of the resolution of the returned promise.

**Comment by kriskowal** [comment]
> Can't allow unprivileged code to cause the enclosing Node process to exit.
> 
> The sniffing here is necessarily host specific, so we can incrementally add hosts over time. What are your thoughts on what we should do on xsnap, where the entire console is our own creation anyway? Is it even possible on current xsnap to catch these errors?

Throwing an error out of the top of an event in Node.js causes the enclosing process to exit. This is necessary to preserve the current behavior on Node.js, when overriding the uncaughtException handler. Otherwise, a Node.js server would require a <kbd>＾C</kbd> to be explicitly pressed after an error corrupts its integrity. We may have some more flexibility in the design of Endo daemons.

**Comment by kriskowal** [comment]
Summarizing out-of-band conversation with @erights and @dckc:

We’ve decided that the behavior for uncaught errors needs to be parameterized on lockdown options and default to platform-emulation, with the right reserved to change the behavior. The behaviors may be `report`, `reload`, `exit`, `abort`, or `platform`.

- `report` *just* report the error to the virtualized console, revealing the stack trace to the underlying platform console, whatever was present when the shim was initialized.
- `reload` reboots, restarts, or reloads. (aspirational goal)
- `exit` report and exit with an exit code, -1 if no exit code was previously supplied. On the web, this amounts to hitting a breakpoint if the debugger is open and navigating away.
- `abort` report and exit with a core dump or navigate away. In Node.js, `process.abort()`.
- `platform` is consistent with the underlying behavior when an exception is not caught. On the web, this is an error report and resume. On Node.js, it’s an error report and exit. This will be the provisional default.

**Comment by kriskowal** [comment]
I’ve implemented an `errorTrapping` option for `lockdown`, as described in my comment about intent.

I was flummoxed by a failing integration test for a while. The problem was that Parcel saw the `process` free variable and tried a little too hard to be helpful. Parcel included a `process` shim as a CommonJS peer in its generated bundle, and that somehow forced the whole bundle out of strict mode and into sloppy mode. Our new fancy test to ensure the strict mode invariant tripped on this.

The solution was to spell `process` as `globalThis.process` and that was sufficient to avert the gaze of 👀📎Clippy.

File: packages/ses/src/error/tame-console.js (hunk 1 above)
Comment (kriskowal) [reply packages/ses/src/error/tame-console.js]: I’ve integrated this change.

File: packages/ses/src/error/tame-console.js (hunk 2 above)
Comment (kriskowal) [reply packages/ses/src/error/tame-console.js]: I believe I’ve addressed this concern, albeit pragmatically, with the `errorTrapping` option. The default is consistent behavior with the underlying platform, which is sometimes inconsistent with this principle. The overrides allow for more principled behavior and we’ll certainly use `report` for Endo daemons.

File: packages/ses/test/test-console-error-trap.js (hunk 3 above)
Comment (kriskowal) [reply packages/ses/test/test-console-error-trap.js]: https://github.com/endojs/endo/issues/805

File: packages/ses/test/test-console-error-trap.js (hunk 4 above)
Comment (kriskowal) [reply packages/ses/test/test-console-error-trap.js]: I’ve addressed this by making the tests more specific.

File: packages/ses/test/test-console-error-trap.js (hunk 5 above)
Comment (kriskowal) [reply packages/ses/test/test-console-error-trap.js:37]: `test.cb` is as I intuited above. `test` expects the return value of the testback to signal that the test has ended either by returning `undefined` or a promise that resolves to `undefined`, whereas `test.cb` is more like `tap`—the test ends only with an explicit call to `t.end()`.

**Review by erights — APPROVED** [review]
LGTM. Glad to see this!
