### PR TITLE
fix(ses): Support an incomplete shimmed globalThis.process

### LINKED ISSUE #1917: Loading SES fails if `globalThis.process` is shimmed
## Describe the bug

Console taming assumes that if `globalThis.process` exists, then we're in node, and get to use some `process` APIs like `.on()` `.exit()` etc.
https://github.com/endojs/endo/blob/2179108cb9247e9499c1f319de907d7cd365f314/packages/ses/src/error/tame-console.js#L97-L126

If `globalThis.process` is shimmed with something like `{env: {FOO: 'bar'}}`, then loading SES fails with `globalThis.process.on` is not a function.

## Expected behavior

Console taming should more fully feature test the Node features it expects

## Platform environment

Browser

## Screenshots

image

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #1917

## Description

Updates packages/ses/src/error/tame-console.js to check for a `globalThis.process.on` function rather than assuming it when `globalThis.process` is defined.

Also updates general patterns for checking `globalThis` properties for better uniformity.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

n/a

### Testing Considerations

n/a

### Upgrade Considerations

n/a

### CODE REVIEW

File: packages/ses/src/error/fatal-assert.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ let abandon;
 // below). Currently it only checks for the `process.abort` or `process.exit`
 // found on Node. It should also sniff for a vat terminating function expected
 // to be found within the start compartment of SwingSet vats. What else?
-if (typeof process === 'object') {
+if (process && typeof process === 'object') {
```
Comment (mhofman) [inline packages/ses/src/error/fatal-assert.js:13]: This is a behavioral change that will cause a `ReferenceError` if not defined.

**Review by mhofman — CHANGES_REQUESTED** [review]
The `fatal-assert.js` change will result in problems on non node environments.

File: packages/ses/src/error/fatal-assert.js (hunk 1 above)
Comment (gibson042) [reply packages/ses/src/error/fatal-assert.js:13]: Ack, nice catch!

File: packages/ses/src/error/tame-console.js [hunk 2]
```diff
@@ -95,21 +95,29 @@ export const tameConsole = (
...
 
   // Node.js
-  if (errorTrapping !== 'none' && globalThis.process !== undefined) {
-    globalThis.process.on('uncaughtException', error => {
+  const globalProcess = globalThis.process;
+  if (
+    errorTrapping !== 'none' &&
+    globalProcess &&
+    typeof globalProcess === 'object' &&
+    typeof globalProcess.on === 'function'
```
[the remark this answers is not in the document]
Comment (gibson042) [reply packages/ses/src/error/tame-console.js:102]: Done.

File: packages/ses/src/error/tame-console.js [hunk 3]
```diff
@@ -95,21 +95,26 @@ export const tameConsole = (
   /* eslint-disable @endo/no-polymorphic-call */
 
   // Node.js
-  if (errorTrapping !== 'none' && globalThis.process !== undefined) {
-    globalThis.process.on('uncaughtException', error => {
+  const globalProcess = globalThis.process || undefined;
+  if (
+    errorTrapping !== 'none' &&
+    typeof globalProcess === 'object' &&
+    typeof globalProcess.on === 'function'
```
Comment (kriskowal) [inline packages/ses/src/error/tame-console.js:102]: Should test for existence of abort and exit as well.

**Review by kriskowal — APPROVED** [review]
With caveats. Thank you!

File: packages/env-options/src/env-options.js [hunk 4]
```diff
@@ -61,22 +61,21 @@ export const makeEnvironmentCaptor = aGlobal => {
...
-              optionName,
-            )}, if present, must have a corresponding string value, got ${q(
-              optionValue,
-            )}`;
-          setting = optionValue;
-        }
+    const globalProcess = aGlobal.process || undefined;
+    const globalEnv =
+      (typeof globalProcess === 'object' && globalProcess.env) || undefined;
+    if (typeof globalEnv === 'object') {
```
[the remark this answers is not in the document]
Comment (mhofman) [reply packages/env-options/src/env-options.js:67]: It doesn't given the `|| undefined`

**Comment by gibson042** [comment]
@mhofman ready for re-review.

**Review by mhofman — APPROVED** [review]
LGTM!
