### PR TITLE
fix(ses): fixup async iterator helpers

### LINKED ISSUE #1289: Anticipate new hidden intrinsics: Iteration helpers
As proposals advance in tc39, some will introduce new hidden intrinsics, starting with Iteration helpers. At the Sep 2022 tc39 meeting, we agreed on a compromise where the proposal provides code for discovering these new hidden intrinsics. The ses-shim would use this code in order to add these hidden intrinsics to the collection of intrinsics to be checked against the whitelist and hardened. This compromise is only needed until the getIntrinsics proposal lands, which will provide a unified mechanism for discover all intrinsics.

https://github.com/tc39/proposal-iterator-helpers/pull/235/files is an adequate approximation of this agreement. We need to modify it so it doesn't fail if run on a system in which these are not present. With that modification, we should adopt it into the ses-shim well ahead of anyone shipping an engine that implements the Iterator helpers proposal. 

(During the Google era of SES, we had a bad vulnerability do to failure to add code to discover the async generator intrinsics until after it was shipping. Fortunately, it was responsibly disclosed and we have no reason to believe it was ever maliciously exploited.)

Attn @michaelficarra @ljharb @kriskowal

### LINKED ISSUE #1669: How to run .cjs shims strict?
To write tests for https://github.com/endojs/endo/pull/1655 , I import some shims from core-js. However, core-js is written in common lisp style modules, which by default are evaluated as sloppy code. As a result, even if the shims in question were otherwise safe and compatible with Hardened JS, this aspect makes them grossly unsafe. Fortunately, the SES shim by default will fail to initialize if it encounters apparently primordial sloppy functions. This fails safe.

At https://github.com/endojs/endo/pull/1655#discussion_r1253755342 @mhofman suggests that we run these as strict code. Presumably, to support LavaMoat, we already know how to do that. How should I modify the test cases from that PR?

### PR DESCRIPTION
**Pull request by mhofman**
#1655 introduced support for iterator helpers, but due to a limitation in the core-js shim usage, the async iterator helper test was disabled, and the PR missed a couple errors in the implementation of permits for the async iterator helpers.

This PR fixes these errors, and addresses the testing limitations so that the iterator helpers tests (both sync and async) can behave more like normal tests.

Closes #1669 
Closes #1289

### CODE REVIEW

File: packages/ses/src/get-anonymous-intrinsics.js [hunk 1]
```diff
@@ -146,7 +146,7 @@ export const getAnonymousIntrinsics = () => {
     );
   }
 
-  if (globalThis.AsyncInterator) {
+  if (globalThis.AsyncIterator) {
```
Comment (erights) [inline packages/ses/src/get-anonymous-intrinsics.js:149]: Oops! Thanks for catching this.

File: packages/ses/src/permits.js [hunk 2]
```diff
@@ -1317,7 +1317,7 @@ export const permitted = {
 
   // https://github.com/tc39/proposal-async-iterator-helpers
   '%AsyncIteratorHelperPrototype%': {
-    '[[Proto]]': 'Async%IteratorPrototype%',
+    '[[Proto]]': '%AsyncIteratorPrototype%',
```
Comment (erights) [inline packages/ses/src/permits.js:1320]: Oops! Thanks for catching this too.

File: packages/ses/test/enforce-cjs-strict.js [hunk 3]
```diff
@@ -0,0 +1,3 @@
+import module from 'node:module';
+
+module.wrapper[0] += '"use strict";';
```
Comment (erights) [inline packages/ses/test/enforce-cjs-strict.js:3]: Frankly, much less painful than I feared ;)

**Review by erights — APPROVED** [review]
LGTM THANKS!

**Comment by mhofman** [comment]
> Oops! Thanks for catching this.

Well the tests caught it, but I have to admit, it was hard to diagnose because ava caught the exception and didn't print out the details (I assume because we're not using ses-ava here)
